# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.tecnologica-sistemas.com
title: TecnoLogica
email: tecnologica@gmail.com
author: Tecnologica
description: > # "Write an awesome description for your new site here. 
  Tecnologíca es una empresa con más de 30 años de experiencia en sistemas informáticos, 
  controles de acceso y reparación de todo tipo de equipos informáticos.
  Recientemente incorporó el armado de impresoras 3D y venta de partes.
copyright: 'Copyright &copy; 2016 Tecnologica. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#social:
#  - title: MercadoLibre
#    url: http://www.mercadolibre.com.ar
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: linkedin
#    url: 
